### ISSUE TITLE
Add option to alphabetize the generated schema file by model name

### ISSUE THREAD

**Issue by maxh** [loop-payments/prisma-fuse#34]
Problem:

- The ordering of the models in the generated schema file depends on the prisma file load order.
- When directories that contain `.prisma` files are moved around, their models may be reordered in the generated schema file.
- This causes schema diffs and sometimes merge conflicts when there are no real changes.

Proposal:

- Alphabetize the list of models in the generated schema based on model name. We can probably do this with https://github.com/MrLeebo/prisma-ast.

**Comment by brandenc40** [comment]
files are already sorted alphabetically by file name ([link](https://github.com/loop-payments/prisma-fuse/blob/2291b1eeb583f2b8390f72953f011bd6c73e0487/src/fuse.ts#L45)) but i think this is using the full file path for sorting. I think a quicker fix than using AST would just be to sort by the filename without the full file path

**Comment by brandenc40** [comment]
sorting by model would require we load every model into memory before writing to a file. i was trying to avoid that by using data streams

**Comment by maxh** [comment]
Ah gotcha. Maybe not worth the performance hit.

Well, sorting by file base name seems like an improvement worth doing.
